package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Caja.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//

public class Caja {

    private int IdCaja;
    private String IdEmpleado;
    private String Estado;

    public Caja(int IdCaja, String IdEmpleado, String estado) {
        this.IdCaja = IdCaja;
        this.IdEmpleado = IdEmpleado;
        this.Estado = estado;
    }

    /**
     * @return the IdCaja
     */
    public int getIdCaja() {
        return IdCaja;
    }

    /**
     * @param IdCaja the IdCaja to set
     */
    public void setIdCaja(int IdCaja) {
        this.IdCaja = IdCaja;
    }

    /**
     * @return the IdEmpleado
     */
    public String getIdEmpleado() {
        return IdEmpleado;
    }

    /**
     * @param IdEmpleado the IdEmpleado to set
     */
    public void setIdEmpleado(String IdEmpleado) {
        this.IdEmpleado = IdEmpleado;
    }

    /**
     * @return the Estado
     */
    public String getEstado() {
        return Estado;
    }

    /**
     * @param Estado the Estado to set
     */
    public void setEstado(String Estado) {
        this.Estado = Estado;
    }
    @Override
        public String toString()
        {
            return String.valueOf(IdCaja);
        }
}
