package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Caja.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//

import Clases.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Caja_ABMC {
    private Conexion conexion = new Conexion();
    private Connection con;
    private Statement st;
    private ResultSet rs;

    public Caja_ABMC() {
        try{
            if((con = conexion.getConexionMYSQL())==null){
                JOptionPane.showMessageDialog(null,"Error con la conexion a la BD");
                return;
            }
            st = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean insert(int IdCaja, int IdEmpleado, String estado){
        try {
            String query = "INSERT INTO caja VALUES("+IdCaja+","+IdEmpleado+",'"+estado+"',0)";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public ResultSet selectXtodas(){
        try {
            String query = "SELECT a.IdCaja, b.Nombre, a.estado FROM caja as a, empleado as b WHERE (a.IdEmpleado=b.IdEmpleado) AND (a.indexB=0) AND (estado LIKE 'abierto')";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ResultSet IdNombre(String nom){
        try {
            String query = "SELECT IdCaja FROM caja WHERE (estado like '"+nom+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
            
        public boolean delete(int id){
        try {
            String query = "UPDATE caja SET"
                    + " indexB = '1'"
                    + " WHERE IdCaja = '"+id+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public boolean update(int IdCaja, int IdEmpleado, String estado){
        try {
            String query = "UPDATE caja SET"
                    + " IdEmpleado = '"+IdEmpleado+"',"
                    + " estado = '"+estado+"' WHERE IdCaja = '"+IdCaja+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
