package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.JOptionPane;



public class Cliente_ABMC {
    private Conexion conexion = new Conexion();
    private Connection con;
    private Statement st;
    private ResultSet rs;

    public Cliente_ABMC() {
        try{
            if((con = conexion.getConexionMYSQL())==null){
                JOptionPane.showMessageDialog(null,"Error con la conexion a la BD");
                return;
            }
            st = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean insert(int id,String Tid,String nombre,String apellido,String direccion,String fechaN, int telefono,String email){
        try {
            String query = "INSERT INTO cliente VALUES('"+id+"','"+Tid+"','"+nombre+"','"+apellido+"','"+direccion+"','"+fechaN+"',"+telefono+",'"+email+"',0)";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public ResultSet selectXtodas(){
        try {
            String query = "SELECT id_cliente,tipoId,Nombre,Apellido,direccion,fechaNacimiento,telefono,email FROM cliente WHERE indexB='0'";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ResultSet IdNombre(String nom){
        try {
            String query = "SELECT id_cliente FROM cliente WHERE (Nombre like '"+nom+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
            
    
    public boolean delete(int id){
        try {
            String query = "UPDATE cliente SET"   
                    + " indexB = '1' WHERE id_cliente = '"+id+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public boolean update(int id,String Tid,String nombre,String apellido,String direccion,String fechaN, int telefono,String email){
        try {
            String query = "UPDATE cliente SET"                    
                    + " tipoId = '"+Tid+"',"
                    + " Nombre = '"+nombre+"',"
                    + " Apellido = '"+apellido+"',"
                    + " direccion = '"+direccion+"',"
                    + " fechaNacimiento = '"+fechaN+"', "
                    + " telefono = '"+telefono+"', "
                    + " email = '"+email+"' WHERE id_cliente = '"+id+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
