package Clases;
//
//

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Detalle.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//




public class Detalle_ABMC {
    private Clases.Conexion conexion = new Clases.Conexion();
    private Connection con;
    private Statement st;
    private ResultSet rs;

    public Detalle_ABMC() {
        try{
            if((con = conexion.getConexionMYSQL())==null){
                JOptionPane.showMessageDialog(null,"Error con la conexion a la BD");
                return;
            }
            st = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean insert(int numF, int idP, int cantidad, double precio){
        try {
            String query = "INSERT INTO detalle VALUES(NULL,"+numF+","+idP+","+cantidad+",'"+precio+"',0)";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public ResultSet selectXtodas(){
        try {
            String query = "SELECT num_detalle,num_factura,id_producto,cantidad,precio FROM detalle WHERE indexB=0";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ResultSet IdNombre(int nom){
        try {
            String query = "SELECT num_detalle FROM detalle WHERE num_factura ='"+nom+"'";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
            
        public boolean delete(int id){
        try {
            String query = "UPDATE detalle SET"
                    + " indexB = '1'"                   
                    + " WHERE num_factura = '"+id+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public boolean update(int numD, int numF, int idP, int cantidad, double precio){
        try {
            String query = "UPDATE detalle SET"
                    + " num_factura = '"+numF+"',"
                    + " id_producto = '"+idP+"' "
                    + " cantidad = '"+cantidad+"' "
                    + " precio ='"+precio+"' WHERE num_detalle = '"+numD+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
