package Clases;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empleado.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//




public class Empleado {
	private int IdEmpleado;
	private String Nombre;
	private String Apellido;
	private int CI;
	private String FechaIngreso;
	
        public Empleado(int idempleado, String nombre, String apellido, int ci, String fecha){
            this.IdEmpleado=idempleado;
            this.Nombre=nombre;
            this.Apellido=apellido;
            this.CI=ci;
            this.FechaIngreso=fecha;
        }

    /**
     * @return the IdEmpleado
     */
    public int getIdEmpleado() {
        return IdEmpleado;
    }

    /**
     * @param IdEmpleado the IdEmpleado to set
     */
    public void setIdEmpleado(int IdEmpleado) {
        this.IdEmpleado = IdEmpleado;
    }

    /**
     * @return the Nombre
     */
    public String getNombre() {
        return Nombre;
    }

    /**
     * @param Nombre the Nombre to set
     */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /**
     * @return the Apellido
     */
    public String getApellido() {
        return Apellido;
    }

    /**
     * @param Apellido the Apellido to set
     */
    public void setApellido(String Apellido) {
        this.Apellido = Apellido;
    }

    /**
     * @return the CI
     */
    public int getCI() {
        return CI;
    }

    /**
     * @param CI the CI to set
     */
    public void setCI(int CI) {
        this.CI = CI;
    }

    /**
     * @return the FechaIngreso
     */
    public String getFechaIngreso() {
        return FechaIngreso;
    }

    /**
     * @param FechaIngreso the FechaIngreso to set
     */
    public void setFechaIngreso(String FechaIngreso) {
        this.FechaIngreso = FechaIngreso;
    }
    @Override
        public String toString()
        {
            return String.valueOf(IdEmpleado);
        }
        
}
