package Clases;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empleado.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//




public class Empleado_ABMC {
    private Clases.Conexion conexion = new Clases.Conexion();
    private Connection con;
    private Statement st;
    private ResultSet rs;

    public Empleado_ABMC() {
        try{
            if((con = conexion.getConexionMYSQL())==null){
                JOptionPane.showMessageDialog(null,"Error con la conexion a la BD");
                return;
            }
            st = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean insert(String nombre, String apellido, int ci, String fecha){
        try {
            String query = "INSERT INTO empleado VALUES(NULL,'"+nombre+"','"+apellido+"','"+ci+"','"+fecha+"',0)";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public ResultSet selectXtodas(){
        try {
            String query = "SELECT IdEmpleado,Nombre,Apellido,CI,FechaIngreso FROM empleado WHERE indexB='0'";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ResultSet IdNombre(String nom){
        try {
            String query = "SELECT IdEmpleado FROM empleado WHERE (Nombre LIKE '"+nom+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
            
        public boolean delete(int id){
        try {
            String query = "UPDATE empleado SET"
                    + " indexB ='1' WHERE IdEmpleado = '"+id+"';";
            st.executeUpdate(query);
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public boolean update(int idempleado, String nombre, String apellido, int ci, String fecha){
        try {
            String query = "UPDATE empleado SET"
                    + " Nombre = '"+nombre+"',"
                    + " Apellido = '"+apellido+"' "
                    + " CI = '"+ci+"' "
                    + " FechaIngreso ='"+fecha+"' WHERE IdEmpleado = '"+idempleado+"';";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
