package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factura.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//

public class Factura {

    private int num_factura;
    private int IdCliente;
    private String fecha;
    private int IdCaja;

    public Factura(int num, int idcliente, String fecha, int idcaja) {
        this.num_factura=num;
        this.IdCliente=idcliente;
        this.IdCaja=idcaja;
        this.fecha=fecha;
    }

    /**
     * @return the num_factura
     */
    public int getNum_factura() {
        return num_factura;
    }

    /**
     * @param num_factura the num_factura to set
     */
    public void setNum_factura(int num_factura) {
        this.num_factura = num_factura;
    }

    /**
     * @return the IdCliente
     */
    public int getIdCliente() {
        return IdCliente;
    }

    /**
     * @param IdCliente the IdCliente to set
     */
    public void setIdCliente(int IdCliente) {
        this.IdCliente = IdCliente;
    }

    /**
     * @return the fecha
     */
    public String getFecha() {
        return fecha;
    }

    /**
     * @param fecha the fecha to set
     */
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the IdCaja
     */
    public int getIdCaja() {
        return IdCaja;
    }

    /**
     * @param IdCaja the IdCaja to set
     */
    public void setIdCaja(int IdCaja) {
        this.IdCaja = IdCaja;
    }
    @Override
        public String toString()
        {
            return String.valueOf(num_factura);
        }
}
