package Clases;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Producto.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.JOptionPane;



public class Producto_ABMC {
    private Conexion conexion = new Conexion();
    private Connection con;
    private Statement st;
    private ResultSet rs;
    
    public Producto_ABMC() {
        try{
            if((con = conexion.getConexionMYSQL())==null){
                JOptionPane.showMessageDialog(null,"Error con la conexion a la BD");
                return;
            }
            st = con.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public boolean insert(int cod, String nombre, double precio, int stock, int proveedor){
        try {
            String query = "INSERT INTO producto VALUES('"+cod+"','"+nombre+"','"+precio+"','"+stock+"','"+proveedor+"',0);";
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    
    public ResultSet selectXtodas(){
        try {
            String query = "SELECT id_producto,nombre,precio,stock,IdProveedor FROM producto WHERE indexB=0";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ResultSet selectXtodasXID(int n){
        try {
            String query = "SELECT nombre, precio FROM producto WHERE (id_producto='"+n+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }        
    
    public ResultSet ReqID(String n){
        try {
            String query = "SELECT id_producto FROM producto WHERE (nombre LIKE '"+n+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    } 
    
    public boolean delete(int id){
        try {
            String query = "UPDATE producto SET"
                    + " indexB = '1'"
                    + " WHERE id_producto= '"+id+"'";    
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    public boolean ReducirStock(int id, int stock){
        try {
            String query = "UPDATE producto SET"
                    + " stock = "+stock+""
                    + " WHERE id_producto= '"+id+"'";                    
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    public ResultSet ObtenerStock(String n){
        try {
            String query = "SELECT stock FROM producto WHERE (nombre LIKE '"+n+"') AND (indexB=0)";
            rs = st.executeQuery(query);
            return rs;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    } 
    
    public boolean update(int id, String nombre, double precio, int stock, int proveedor){
        try {
            String query = "UPDATE producto SET"
                    + " nombre = '"+nombre+"',"
                    + " precio = "+precio+","
                    + " stock = "+stock+","
                    + " proveedor = "+proveedor+" WHERE id_producto= '"+id+"'";                    
            st.executeUpdate(query);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
