package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Proveedor.java
//  @ Date : 14/11/2016
//  @ Author : 
//
//

public class Proveedor {

    private int IdProveedor;
    private String Pais;
    private String Area;

    public Proveedor(int Idproveedor, String pais, String area) {
        this.IdProveedor = Idproveedor;
        this.Pais = pais;
        this.Area = area;
    }

    /**
     * @return the IdProveedor
     */
    public int getIdProveedor() {
        return IdProveedor;
    }

    /**
     * @param IdProveedor the IdProveedor to set
     */
    public void setIdProveedor(int IdProveedor) {
        this.IdProveedor = IdProveedor;
    }

    /**
     * @return the Pais
     */
    public String getPais() {
        return Pais;
    }

    /**
     * @param Pais the Pais to set
     */
    public void setPais(String Pais) {
        this.Pais = Pais;
    }

    /**
     * @return the Area
     */
    public String getArea() {
        return Area;
    }

    /**
     * @param Area the Area to set
     */
    public void setArea(String Area) {
        this.Area = Area;
    }
    @Override
        public String toString()
        {
            return String.valueOf(IdProveedor);
        }
}
